import Searchbar from "../components/Searchbar";

function Home() {

  return (

    <div
      className="min-h-screen text-white px-8"
      style={{
        backgroundColor: "#070B14",
        backgroundImage: `
        radial-gradient(circle at top right, rgba(168,85,247,.18), transparent 35%),
        radial-gradient(circle at bottom left, rgba(6,182,212,.12), transparent 35%)
        `
      }}
    >

      <div className="max-w-6xl mx-auto pt-24">

        <div className="text-center">

          <span className="bg-violet-500/20 text-violet-300 px-5 py-2 rounded-full text-sm">

            🚀 AI Powered GitHub Repository Analyzer

          </span>

          <h1 className="text-7xl font-black mt-8 leading-tight">

            AI Codebase

            <br />

            Mentor

          </h1>

          <p className="text-gray-400 text-xl mt-8 max-w-3xl mx-auto leading-9">

            Understand any GitHub repository in minutes using Artificial Intelligence.

            Get AI-powered summaries, difficulty analysis, required skills,

            learning roadmap and project recommendations.

          </p>

        </div>

        <div className="mt-14 flex justify-center">

          <Searchbar />

        </div>

        {/* FEATURES */}

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mt-20">

          <div className="bg-[#151A23] border border-[#232A36] rounded-3xl p-6">

            <div className="text-4xl mb-4">📖</div>

            <h3 className="font-bold text-xl">

              AI Summary

            </h3>

            <p className="text-gray-400 mt-3">

              Understand repositories instantly with AI-generated summaries.

            </p>

          </div>

          <div className="bg-[#151A23] border border-[#232A36] rounded-3xl p-6">

            <div className="text-4xl mb-4">📈</div>

            <h3 className="font-bold text-xl">

              Difficulty

            </h3>

            <p className="text-gray-400 mt-3">

              Know whether a project is Beginner, Intermediate or Advanced.

            </p>

          </div>

          <div className="bg-[#151A23] border border-[#232A36] rounded-3xl p-6">

            <div className="text-4xl mb-4">🛠</div>

            <h3 className="font-bold text-xl">

              Skills

            </h3>

            <p className="text-gray-400 mt-3">

              Discover technologies you should learn before contributing.

            </p>

          </div>

          <div className="bg-[#151A23] border border-[#232A36] rounded-3xl p-6">

            <div className="text-4xl mb-4">🗺</div>

            <h3 className="font-bold text-xl">

              Roadmap

            </h3>

            <p className="text-gray-400 mt-3">

              Follow a personalized roadmap generated by AI.

            </p>

          </div>

        </div>

        {/* FOOTER */}

        <div className="text-center mt-24 pb-10">

          <p className="text-gray-500">

            Built with ❤️ using React • Tailwind CSS • GitHub API • Gemini AI

          </p>

        </div>

      </div>

    </div>

  );

}

export default Home;